Remove @Nullable on return types of `elementFromDeclaration` in `TreeUtils`
eisop/checker-framework pull request #358
Opened 2022-11-04 02:49 UTC by zcai1

2022-11-04 02:50 UTC, zcai1 commented
It seems whole program inference may scan unprocessed trees?

2022-11-04 20:33 UTC, wmdietl requested changes
Thanks for these cleanups, in particular for also removing the now redundant asserts.
There is one failure:
````
> Task :dataflow:checkNullness
/__w/1/s/dataflow/src/main/java/org/checkerframework/dataflow/expression/JavaExpression.java:712: warning: [nullness:unneeded.suppression] warning suppression "nullness:argument" is not used by NullnessChecker
        @SuppressWarnings("nullness:argument") // elementFromDeclaration is non-null for a parameter
````

2022-11-05 16:37 UTC, wmdietl approved these changes
Thanks!

2022-11-05 16:37 UTC, wmdietl commented on checker/src/main/java/org/checkerframework/checker/guieffect/GuiEffectVisitor.java
```suggestion
        // Check for conflicting (multiple) annotations
```

2022-11-05 16:39 UTC, wmdietl commented on checker/src/main/java/org/checkerframework/checker/guieffect/GuiEffectVisitor.java
>          }
```suggestion
        }

```

2022-11-05 21:06 UTC, merged