Run JSpecify Conformance Tests on nullness checker
eisop/checker-framework pull request #709
Opened 2024-02-14 00:54 UTC by rohan-shettyy

- Extended JSpecify conformance test framework to run the conformance test suite on EISOP nullness checker
- Generates report to `checker/report/ConformanceTest-report.txt`
- Use standard distribution of Guava

2024-02-14 22:33 UTC, wmdietl requested changes
Thanks for starting this!
CI is failing with:
````
A problem occurred configuring project ':checker'.
> The value for task ':checker:compileJava' property 'javaCompiler' is final and cannot be changed any further.
````

Is it working for you locally? I don't immediately see which of your changes causes this.

2024-02-14 22:33 UTC, wmdietl commented on checker/src/test/java/org/checkerframework/checker/test/junit/NullnessJSpecifyConformanceTest.java
> +                    "-AshowTypes");
```suggestion
                    "-AassumePure",
                    "-Adetailedmsgtext");
```

These options don't exist in EISOP: `"-AcheckImpl", "-Astrict", "-AshowTypes"`.
Not clear what the warning suppression would do.

2024-02-14 22:33 UTC, wmdietl commented on checker/build.gradle
> +    environment "JSPECIFY_CONFORMANCE_TEST_MODE", "WRITE"
Why is this set to `WRITE`? That would overwrite the report file. Instead, we want to check for mismatches between the current execution and the existing report.

2024-02-14 22:33 UTC, wmdietl commented on checker/build.gradle
> +task unzipConformanceTestSuite(group: 'Verification') {
Please add `JSpecify` to these tasks and their descriptions.

2024-02-14 22:33 UTC, wmdietl commented on checker/build.gradle
> +        into "${buildDir}/conformance-test-suite"
How about `jspecify-conformance-tests`? That's closer to the artifact name.

2024-02-14 22:33 UTC, wmdietl commented on checker/build.gradle
> +task unzipConformanceTestSuite(group: 'Verification') {
Should this task have a `group`? Tasks with a group are shown in `gradlew tasks`. Is this task ever directly useful?

2024-02-14 22:33 UTC, wmdietl commented on checker/build.gradle
> +    include '**/*ConformanceTest.class'
Make this the full name, to make it easier to find and consistent with the `exclude` above.

2024-02-14 22:33 UTC, wmdietl commented on checker/build.gradle
> +            "ConformanceTest.deps"  : fileTree("tests/nullness-jspecifyconformance/deps").join(":")
What dependencies is this picking up?

2024-02-14 22:33 UTC, wmdietl commented on checker/build.gradle
> +            "ConformanceTest.report": "${projectDir}/report/ConformanceTest-report.txt",
How about putting the file here: `"${projectDir}/src/test/resources/jspecify-conformance-test-report.txt"`?

2024-02-14 22:33 UTC, wmdietl commented on checker/src/test/java/org/checkerframework/checker/test/junit/NullnessJSpecifyConformanceTest.java
> +    private final Path testDir;
The CI will complain about missing javadoc. Please add some description to all fields and methods.

2024-02-14 22:33 UTC, wmdietl commented on checker/src/test/java/org/checkerframework/checker/test/junit/NullnessJSpecifyConformanceTest.java
> +final class FinalReportedFact extends ReportedFact {
What is the `Final` referring to?

2024-02-15 18:58 UTC, rohan-shettyy commented
Added a new commit addressing this feedback.

> Is it working for you locally? I don't immediately see which of your changes causes this.

Yes, this works locally. I am also not sure what causes the failure.

2024-02-18 00:06 UTC, wmdietl reviewed
Thanks for the improvements!
I noticed that you made the PR from your forks `master` branch. You should keep your master clean and in sync with eisop/master. Create a local feature branch for each PR you'll create.

2024-02-18 00:06 UTC, wmdietl commented on checker/build.gradle
> +    description 'Runs the conformance tests.'
```suggestion
    description 'Runs the JSpecify conformance tests.'
```

2024-02-18 00:06 UTC, wmdietl commented on checker/build.gradle
> +tasks.register('unzipJSpecifyConformanceTestSuite', Copy) {
I tried this different (maybe lazily evaluated) task syntax, but it didn't fix our CI problem. Feel free to undo those changes.

The offending line is [here](https://github.com/eisop/checker-framework/blob/e5bfb16b1076756288ce847f25d50df5d3a682c1/build.gradle#L393). From the documentation it sounds like that property should be settable multiple times...

Can you try minimizing what change introduces the problem? E.g. only have the tasks, but don't add the dependency on `test`, remove one of the tasks, etc. until you have a working CI.

2024-02-22 20:30 UTC, rohan-shettyy commented
Removing the tasks dependency and the `runJSpecifyConformanceTests` task individually does not remove the error. Attempting to remove the unzip task gives an error:

```
Execution failed for task ':checker:compileTestJava'.
> Could not resolve all files for configuration ':checker:testCompileClasspath'.
   > Could not resolve org.jspecify.conformance:conformance-test-framework:0.0.0-SNAPSHOT.
     Required by:
         project :checker
      > No matching variant of org.jspecify.conformance:conformance-test-framework:0.0.0-SNAPSHOT:20240207.191836-12 was found. The consumer was configured to find a library for use during compile-time, compatible with Java 8, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally but:
          - Variant 'apiElements' capability org.jspecify.conformance:conformance-test-framework:0.0.0-SNAPSHOT declares a library for use during compile-time, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 9 and the consumer needed a component, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
          - Variant 'runtimeElements' capability org.jspecify.conformance:conformance-test-framework:0.0.0-SNAPSHOT declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 9 and the consumer needed a component, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
```

Could this be an issue with the conformance-test-framework artifact?

2024-02-23 23:08 UTC, wmdietl commented
> Could this be an issue with the conformance-test-framework artifact?

As just discussed, let's try adding a version check.
We don't have a 9+ variable [here](https://github.com/eisop/checker-framework/blob/e5bfb16b1076756288ce847f25d50df5d3a682c1/build.gradle#L41) yet, so add that there.

2024-03-28 02:39 UTC, wmdietl requested changes
Thanks!

2024-03-28 02:39 UTC, wmdietl commented on checker/src/test/resources/jspecify-conformance-test-report.txt
> +# 14 pass; 100 fail; 114 total; 12.3% score
This file is no longer needed, right?

2024-03-28 02:39 UTC, wmdietl commented on checker/bin-devel/test-jspecify-conformance.sh
> +./gradlew clean test --console=plain -PcfLocal
Line ending.

2024-03-28 02:39 UTC, wmdietl commented on checker/bin-devel/test-jspecify-conformance.sh
> +./gradlew clean test --console=plain -PcfLocal
`clean` isn't necessary.

2024-03-28 02:39 UTC, wmdietl commented on build.gradle
> +    maven { url 'https://s01.oss.sonatype.org/content/repositories/snapshots'}
Changes in this file aren't necessary any more.

2024-03-28 02:39 UTC, wmdietl commented on azure-pipelines.yml
> +  steps:
```suggestion
    vmImage: 'ubuntu-latest'
  container: wmdietl/cf-ubuntu-jdk21:latest
  steps:
```

To be consistent with all the other builds.

2024-03-28 02:39 UTC, wmdietl commented on azure-pipelines.yml
> +- job: jspecify_conformance
```suggestion
- job: jspecify_conformance_jdk21
```

Also change above. Okay to test with only one version, but follow the same naming convention to make it clear.

2024-04-06 00:09 UTC, merged