Don't recursive when type parameter extends the class itself
eisop/checker-framework pull request #788
Opened 2024-06-21 22:22 UTC by Ao-senXiong

Fixes #778

2024-08-19 20:34 UTC, Ao-senXiong commented
This PR fixes PICO's crash bug.

2024-08-19 21:18 UTC, Ao-senXiong commented
This also fixes [#443's comment](https://github.com/eisop/checker-framework/issues/433#issuecomment-1464084330)

2024-08-23 20:25 UTC, wmdietl requested changes
As discussed, similar code that uses wildcards instead of raw types still crashes.

2025-02-24 14:45 UTC, wmdietl requested changes
Thanks!

2025-02-24 14:45 UTC, wmdietl commented on framework/tests/viewpointtest/RawtypeInstantiation.java
> +public class RawtypeInstantiation<C extends RawtypeInstantiation<C>> {
Can you think of a better class name? The key isn't rawness, it's the `C extends R<C>` bound, right?

2025-02-24 14:45 UTC, wmdietl commented on framework/tests/viewpointtest/RawtypeInstantiation.java
> +    void foo() {
Can you pick better names than `foo` and `bar`?

2025-02-24 14:45 UTC, wmdietl commented on framework/tests/viewpointtest/RawtypeInstantiation.java
> +        // :: warning: (cast.unsafe.constructor.invocation)
All these warnings distract from the point of this test. Can you add a suitable constructor and suppress the warning there once?

2025-02-24 14:45 UTC, wmdietl commented on framework/tests/viewpointtest/RawtypeInstantiation.java
> +        RawtypeInstantiation<?> wildcardInstance = new @A RawtypeInstantiation<D>();
How do these tests ensure the proper viewpoint adaptation happened?

2025-02-24 14:45 UTC, wmdietl commented on framework/src/main/java/org/checkerframework/framework/type/AbstractViewpointAdapter.java
> +        try {
Are there really exceptions that can happen in this code? Adding these large try blocks makes it hard to see what changed.

2025-03-25 22:30 UTC, Ao-senXiong commented on framework/tests/viewpointtest/RawtypeInstantiation.java
> +        // :: warning: (cast.unsafe.constructor.invocation)
Updated the code, thanks!

2025-03-25 22:30 UTC, Ao-senXiong commented on framework/tests/viewpointtest/RawtypeInstantiation.java
> +    void foo() {
Updated, thanks!

2025-03-25 22:30 UTC, Ao-senXiong commented on framework/tests/viewpointtest/RawtypeInstantiation.java
> +public class RawtypeInstantiation<C extends RawtypeInstantiation<C>> {
Removed, thanks!

2025-03-25 22:33 UTC, Ao-senXiong commented on framework/src/main/java/org/checkerframework/framework/type/AbstractViewpointAdapter.java
> +        try {
OK, I have removed try blocks.

2025-03-25 22:35 UTC, Ao-senXiong commented on framework/tests/viewpointtest/RawtypeInstantiation.java
> +        RawtypeInstantiation<?> wildcardInstance = new @A RawtypeInstantiation<D>();
I will open another issue for testing viewpoint adaptation with generics.

2025-03-26 16:13 UTC, wmdietl requested changes
Thanks for getting back to this.

2025-03-26 16:13 UTC, wmdietl commented on framework/src/main/java/org/checkerframework/framework/type/AbstractViewpointAdapter.java
> +    /** The set of type parameter that have been visited. */
The `type parameter` is misleading... all visited types are added, not just type parameters. If it is only for type parameters, can you use a more specific type?

2025-03-26 16:13 UTC, wmdietl commented on framework/src/main/java/org/checkerframework/framework/type/AbstractViewpointAdapter.java
> +    private final Set<AnnotatedTypeMirror> visitedTypes = new HashSet<>();
Looking at https://github.com/eisop/checker-framework/blob/d970bdf063f93f66a08bc964efd15d6050873a28/framework/src/main/java/org/checkerframework/framework/type/visitor/AnnotatedTypeScanner.java#L164 should this be `Collections.newSetFromMap(new IdentityHashMap<>())`? To avoid confusing two types that are equal but different objects?

2025-03-31 21:54 UTC, Ao-senXiong commented on framework/src/main/java/org/checkerframework/framework/type/AbstractViewpointAdapter.java
> +    private final Set<AnnotatedTypeMirror> visitedTypes = new HashSet<>();
I tried this solution but it did not work out. The reason is [here](https://github.com/eisop/checker-framework/blob/908f57414132cf25a9c7ee08e62eda5171a9cfb6/framework/src/main/java/org/checkerframework/framework/type/AbstractViewpointAdapter.java#L307) we are using a shallow copy and then the identities are different for the same declaration.

2025-05-31 22:54 UTC, wmdietl requested changes

2025-05-31 22:54 UTC, wmdietl commented on framework/src/main/java/org/checkerframework/framework/type/AbstractViewpointAdapter.java
>              AnnotatedDeclaredType adt = (AnnotatedDeclaredType) declared.shallowCopy();
Can this be re-ordered to avoid the creation of the shallow copy if it isn't used at all?

2025-05-31 22:54 UTC, wmdietl commented on framework/src/main/java/org/checkerframework/framework/type/AbstractViewpointAdapter.java
> +    private final Set<AnnotatedTypeMirror> visitedTypes = new HashSet<>();
Can you compare before doing the shallow copy?

2026-05-24 16:52 UTC, aosen-xiong commented on framework/src/main/java/org/checkerframework/framework/type/AbstractViewpointAdapter.java
> +    private final Set<AnnotatedTypeMirror> visitedTypes = new HashSet<>();
updated.

2026-05-24 16:52 UTC, aosen-xiong commented on framework/src/main/java/org/checkerframework/framework/type/AbstractViewpointAdapter.java
> +            }
updated.

2026-05-24 16:52 UTC, aosen-xiong commented on framework/src/main/java/org/checkerframework/framework/type/AbstractViewpointAdapter.java
> +        }
updated.

2026-05-24 16:52 UTC, aosen-xiong commented on framework/src/main/java/org/checkerframework/framework/type/AbstractViewpointAdapter.java
>              return result;
updated.

2026-05-24 16:52 UTC, aosen-xiong commented on framework/src/main/java/org/checkerframework/framework/type/AbstractViewpointAdapter.java
>          return rhs;
updated.

2026-05-24 16:57 UTC, aosen-xiong commented on docs/CHANGELOG.md
> +eisop#778, eisop#1051, eisop#1115, eisop#1180.
Moved up an entry.

2026-05-24 16:58 UTC, aosen-xiong commented on framework/src/main/java/org/checkerframework/framework/type/AbstractViewpointAdapter.java
>              AnnotatedDeclaredType adt = (AnnotatedDeclaredType) declared.shallowCopy();
Done. The visited-type check now happens before `declared.shallowCopy()`, so the shallow copy is only created when it will actually be used.

2026-09-07 09:53 UTC, wmdietl approved these changes
Thanks!

2026-09-07 10:39 UTC, merged