Invoke viewpoint adapter at correct place
eisop/checker-framework pull request #903
Opened 2024-09-09 03:40 UTC by Ao-senXiong

2024-10-03 00:41 UTC, wmdietl requested changes
Can you add some test cases that illustrate what goes wrong without this change?

2024-10-03 00:44 UTC, wmdietl commented on framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
>              // AnnotatedTypes.asMemberOf handles vararg type properly, so we do not need to compute
Can you update this comment and make it understandable?
I'm confused by the ordering of viewpoint adaptation and `con.computeVarargType();`, which is different in the two branches. Is there a reason for this? If so, can you add a comment?
Some test cases with varargs and anonymous classes would be good to cover all these cases explicitly.

2026-06-20 14:08 UTC, aosen-xiong commented on framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java
>              // AnnotatedTypes.asMemberOf handles vararg type properly, so we do not need to compute
Okay, I reverted the change. I think a more principal fix would be the current one.

2026-06-20 15:01 UTC, aosen-xiong commented
This does not fix #828, it is a very deep issue that requires hard investigation.

2026-07-17 01:53 UTC, wmdietl commented on framework/tests/viewpointtest/VarargsConstructor.java
> +            // :: error: (new.class.type.invalid) :: error: (varargs.type.incompatible)
What is the intuition behind this new error? There are no arguments to this constructor invocation, so what is incompatible?

2026-07-17 13:14 UTC, aosen-xiong commented on framework/tests/viewpointtest/VarargsConstructor.java
> +            // :: error: (new.class.type.invalid) :: error: (varargs.type.incompatible)
The err msg is:
```
VarargsConstructor.java:35: error: [new.class.type.invalid]
type annotation [@Lost] can not be applied to object creation

VarargsConstructor.java:35: error: [varargs.type.incompatible]
incompatible types in varargs.
  found   : @Lost Object @Top []
  required: @Lost Object @Top []
```

A zero-argument varargs invocation still creates an implicit empty array. The error occurs because viewpoint adaptation produces `@Lost`, which is non-reflexive in this test checker. With #1173, the error would be gone.

2026-07-17 15:12 UTC, wmdietl commented on framework/tests/viewpointtest/VarargsConstructor.java
> +            // :: error: (new.class.type.invalid) :: error: (varargs.type.incompatible)
What is the connection to #1173? 1173 is about lost receivers for poly declared receiver methods. This is about arrays?

If the var args array is definitely empty, the Lost component type cannot do any harm. It seems overly conservative to forbid this call, doesn't it?

2026-07-24 15:44 UTC, aosen-xiong commented on framework/tests/viewpointtest/VarargsConstructor.java
> +            // :: error: (new.class.type.invalid) :: error: (varargs.type.incompatible)
Because in #1173 we changed Lost to be a subtype of Lost, this `varags.type.incompatible` error message will be gone.

Okay, I see your points. 

I think even after the change in #1173, we should have

1. If the argument is empty, allow the call.
2. If the argument is not empty and the var arg is adapted to have a lost type, reject the call.

2026-08-28 08:32 UTC, wmdietl approved these changes
Thanks!

2026-08-28 09:05 UTC, merged