Format viewpoint test annotations
eisop/checker-framework pull request #940
Opened 2024-10-07 20:14 UTC by Ao-senXiong

Fix #873

2024-10-08 00:18 UTC, wmdietl requested changes
Thanks for looking into this!

2024-10-08 00:18 UTC, wmdietl commented on build.gradle
> +                formatAnnotations().addTypeAnnotation("PolyInitialized").addTypeAnnotation("A").addTypeAnnotation("B").addTypeAnnotation("Bottom").addTypeAnnotation("PolyVP").addTypeAnnotation("Recei
Can you turn this into two arrays: 1) regular type qualifiers that are not in spotless (yet) 2) test type qualifiers that never make sense to add to spotless.
For the second set, can you add a comment/script, that re-creates the array for future additions?
Then, turn the `addTypeAnnotation` into a functional style that passes each array element.

2024-10-08 01:54 UTC, Ao-senXiong commented
Looks like spotless does not allow `addTypeAnnotation` be used as a functional style.
The following code will throw this error, single annotation array is fine and multiple annotations array will cause this problem:
```
// Regular type qualifiers array that are not in Spotless yet
def regularTypeQualifiers = [
        "PolyInitialized"
]

// Test type qualifiers array
def testTypeQualifiers = [
        "PolyVP", "ReceiverDependentQual"
]

def allQualifiers = regularTypeQualifiers + testTypeQualifiers

// Add all type qualifiers to Spotless
allQualifiers.each { qualifier ->
    formatAnnotations().addTypeAnnotation(qualifier)
}
```
```
* What went wrong:
Could not create task ':checker:spotlessJavaCheck'.
Could not create task ':checker:spotlessJava'.
Multiple steps with name 'No line break between type annotation and type' for spotless format 'java'
```

However, I also notice spotless already support a few of our testannotations so I can simplify it.
https://github.com/diffplug/spotless/blob/85a0bebc71dcf59f56f0ac31b8b2507294cff78d/lib/src/main/java/com/diffplug/spotless/java/FormatAnnotationsStep.java#L51

2024-10-09 15:27 UTC, wmdietl approved these changes
Thanks!

2024-10-09 15:27 UTC, merged